FROM python

WORKDIR /docker_relatorio

COPY requirements.txt /docker_relatorio/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /docker_relatorio/

EXPOSE 8002

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"]