
FROM python

WORKDIR /docker_inventario

COPY requirements.txt /docker_inventario/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /docker_inventario/

EXPOSE 8001

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"]