FROM python:3.10-slim

# Instalar dependências do sistema necessárias para o MariaDB

# Diretório de trabalho no container
WORKDIR /docker_cliente

RUN apt-get update && apt-get install -y \
    gcc \
    libmariadb-dev \
    libssl-dev \
    pkg-config 

# Copiar o arquivo requirements.txt
COPY cliente/requirements.txt /docker_cliente/

# Instalar as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do projeto
COPY cliente/ /docker_cliente/

# Expor a porta do servidor
EXPOSE 8000

# Comando para iniciar o servidor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
