
services:
  cliente-api:
    build:
      context: cliente_project/cliente/
      dockerfile: dockerfile
    container_name: cliente-api
    ports:
      - "8000:8000" # Porta externa:interna
    volumes:
      - ./cliente_project/cliente:/docker_cliente # Sincroniza os arquivos locais com o container
    depends_on:
      - db_cliente
    environment:
      - DEBUG=True
      - DB_NAME=cliente_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db_cliente
      - DB_PORT=3306

  db_cliente:
    build:
      context: .
      dockerfile: dockerfile.mariadb
    container_name: cliente-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=cliente_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - cliente_db_data:/var/lib/mysql


volumes:
  cliente_db_data:
